name: CommandSigns
main: org.zonedabone.commandsigns.CommandSigns
authors: [HansAnderson, zonedabone]
version: 1.3.0
commands:
  commandsigns:
    description: CommandSigns commands.
    usage: |
        /commandsigns line<number> - Add a line to your CommandSign clipboard. Right click a sign to activate.
        /commandsigns read - Right click a sign to read the CommandSign text.
        /commandsigns copy - Copy a CommandSigns to your clipboard.
        /commandsigns remove - Right click a sign to remove a CommandSign.
        /commandsigns clear - Clear your CommandSign clipboard.
permissions:
    commandsigns.*:
        description: Gives access to all CommandSigns commands
        children:
            commandsigns.create.*: true
            commandsigns.remove: true
            commandsigns.use.*: true
            commandsigns.group.*: true
    commandsigns.create.*:
        description: Gives access CommandSigns sign creation commands
        children:
            commandsigns.create.regular: true
            commandsigns.create.super: true
    commandsigns.use.*:
        description: Gives access to CommandSigns sign use
        default: true
        children:
            commandsigns.use.regular: true
            commandsigns.use.super: true
    commandsigns.create.regular:
        description: Allows you to create a regular CommandSign
        default: op
    commandsigns.create.super:
        description: Allows you to create a super CommandSign
        default: op
    commandsigns.remove:
        description: Allows you to remove a CommandSign
        default: op
    commandsigns.use.super:
        description: Allows you to use a super CommandSign
        default: op
    commandsigns.group.*:
        description: Allows you to use all group commands
        default: op